name: BetonLangAPI
main: pl.betoncraft.betonlangapi.BetonLangAPI
description: Translations API for Bukkit plugins.
authors: [Co0sh]
website: http://github.com/Co0sh/BetonLangAPI
softdepend: [PlaceholderAPI]
version: 1.2.1
commands:
  language:
    description: Handles languages.
    usage: /<command> [player] [language]
    permission: betonlangapi.command
    aliases: [lang]
  betonlangapi:
    description: Reloads configuration and messages.
    usage: /<command>
    permission: betonlangapi.reload
    aliases: [bla]
permissions:
  betonlangapi.command:
    default: true
  betonlangapi.view:
    default: true
  betonlangapi.self:
    default: true
  betonlangapi.other:
    default: op
  betonlangapi.reload:
    default: op
